spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    username: ${DB_USERNAME:uqi}
    password: ${DB_PASSWORD:Deneme123..}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/book_portal?useSSL=false&allowPublicKeyRetrieval=true
#    hikari:
#      connection-timeout: 12000sc
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#server:
#  port: 5000
#
#spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  datasource:
#    username: uqi
#    password: Meluqi123.
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://awseb-e-zfjukemj4x-stack-awsebrdsdatabase-8sedorozjpf5.chn4qmjggoiv.eu-central-1.rds.amazonaws.com:3306/bookPortal
#  jpa:
#    hibernate:
#      ddl-auto: update